# Generated by Django 4.2.13 on 2024-06-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_item_desc',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
